server:
  port: 5000
  servlet:
    contextPath: /

pg:
  data-source:
    host: truth-or-dare-db.c3lnk3jdj6dv.eu-central-1.rds.amazonaws.com
    port: 5432
    name: postgres
    username: postgres
    password: postgres5005
    driverClassName: org.postgresql.Driver
    jdbcUrl: jdbc:postgresql://${pg.data-source.host}:${pg.data-source.port}/${pg.data-source.name}

spring:
  jpa:
    generate-ddl: true
    hibernate.ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        generate_statistics: false
        format_sql: true

management:
  endpoints:
    jmx:
      exposure:
        include: "health,info"

